# Carrega as definições automaticamente na inicialização
load_definitions = /etc/rabbitmq/definitions.json

# Aumenta o limite de conexões (padrão 1000)
connection_max = 10000

# Log level
log.console.level = info