// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/hello": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/hello";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/hello.tsx": {
    id: "routes/hello";
    page: "/hello";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/hello": typeof import("./app/routes/hello.tsx");
};